name: Markdown

on:
  pull_request:
    paths:
      - '.github/workflows/markdown.yml'
      - '.github/markdownlint.jsonc'
      - '.github/markdown-link-check.json'
      - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: 
  contents: read

jobs:
  markdown-check:
    uses: Open-CMSIS-Pack/workflows-and-actions-collection/.github/workflows/markdown-lint.yml@cleanup
    with:
      lint-config: '.github/markdownlint.jsonc'
      link-check-config: '.github/markdown-link-check.jsonc'
      ignore-files: 'third_party_licenses.md'