name: Release

on:
  push:
    tags:
      - "*"

jobs:
  tpip-check:
    uses: Open-CMSIS-Pack/generator-bridge/.github/workflows/tpip-check.yml@main

  goreleaser:
    needs: [ tpip-check ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
